# Generated by Django 5.1.2 on 2024-11-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_bookrecommendation_book_content_book_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinteractions', to='summaries.book'),
        ),
    ]
