# Generated by Django 5.1.2 on 2024-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_remove_bookprogress_author_remove_bookprogress_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
