# Generated by Django 5.1.2 on 2024-11-20 16:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0009_alter_book_sentiment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRecommendation',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='book',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='favourite_books',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view', 'View Book'), ('bookmark', 'Bookmark Book')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_review'),
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
