# Generated by Django 5.1.2 on 2024-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0010_delete_bookrecommendation_remove_summary_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
