# Generated by Django 5.1.2 on 2024-12-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0011_book_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
