# Generated by Django 5.1.2 on 2024-12-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0013_remove_review_unique_user_book_review_book_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
