# Generated by Django 5.1.2 on 2024-12-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0014_review_book_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.book'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='open_library_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('view', 'View'), ('bookmark', 'Bookmark'), ('detail_click', 'Detail Click')], max_length=50),
        ),
    ]
