# Generated by Django 5.1.2 on 2024-12-08 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0015_useractivity_book_useractivity_open_library_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.book'),
        ),
    ]
