# Generated by Django 5.1.2 on 2024-12-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0016_alter_useractivity_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.book'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='open_library_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
