# Generated by Django 5.1.2 on 2024-12-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0019_book_liked_by_alter_like_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
